source 'https://rubygems.org'
gem 'rake'
gem 'sinatra'
gem 'json'
gem 'sqlite3'
gem 'activerecord'

group :production do
  gem 'unicorn'
end

group :test do
  gem 'rack-test'
  gem 'mocha'
end

group :development do
end
